### PR TITLE
Add JS Beautify to list of repos

### PR DESCRIPTION
**Pull request by aufdenpunkt**

### CODE REVIEW

**Comment by asottile** [comment]
have you proposed this upstream? it would be preferable there instead of a mirror repository.  I'm inclined to decline this and suggest an attempt be made there first

**Comment by aufdenpunkt** [comment]
I'm not sure if I got you right. Is it about the pre-commit hook itself? Or because I have forked the pre-commit.com repo to add the link of the pre-commit hook repo? What do you mean with "proposed this upstream"?

**Comment by asottile** [comment]
for example, adding the `.pre-commit-hooks.yaml` directly to the repository of the tool you're wrapping -- no need to have a mirror repository (that'll be out-of-date / not-locked / etc.).

**Comment by aufdenpunkt** [comment]
Aaah, okay. Makes absolute sense to me. Thanks for clarifying 👍 => Closed

**Pull request closed without merging**
