### PR TITLE
Add `xmllint` check

### PR DESCRIPTION
**Pull request by comkieffer**
Add pre-commit hook to validate xml using xmllint.

### CODE REVIEW

**Comment by asottile** [comment]
dupe of #528

**Comment by comkieffer** [comment]
I'd push to re-open this. Unlike the linked MR, this one installs `xmllint` into a [docker container](https://github.com/comkieffer/pre-commit-xmllint/blob/master/Dockerfile). The linked MR depended on `xmllint` being installed locally AFAIK.

**Comment by asottile** [comment]
ok then:

- please do not name your thing `pre-commit` as it is not affiliated with the project
- it is "pre-commit", not "Pre-commit" or "Pre-Commit"
- the default should probably have `args: [--format]` ?

**Comment by comkieffer** [comment]
1) Naming: I don't have a problem renaming the repo. The `pre-commit-{tool}` naming scheme seems quite common in the existing set of hooks. Are there any guidelines on acceptable names somewhere? 

2) `--format` is not an in-place operation, the result is sent to stdout. Initially, I toyed with a script to wrap `xmllint` to get that behaviour, but couldn't find a simple way to get the name of the file being processed. The linked MR side-steps the issue by not passing any user-supplied `args` to `xmllint` which breaks validation (which needs `--schema schema_url` for example).

**Comment by asottile** [comment]
> The pre-commit-{tool} naming scheme seems quite common in the existing set of hooks.

indeed, I'm trying to be better now about protecting branding than previously

**Comment by comkieffer** [comment]
I've changed the repo url to: https://github.com/comkieffer/xml-linter-hook 

Everything should be good to go.

**Review by asottile — APPROVED** [review]

**Pull request merged**
