### PR TITLE
feat: adding ansys/pre-commit-hooks

### PR DESCRIPTION
**Pull request by RobPasMue**
my new repository:

- [X] is added to the bottom *or* with existing repos from the same account
- [X] contains a license
- [X] is not `language: system`, `language: script`, `language: docker`, or `language: docker_image`
- [ ] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by RobPasMue** [comment]
Hi @asottile - may I ask why this PR was closed?

**Comment by RobPasMue** [comment]
I did see other projects that had ``pre-commit`` on their name, hence my PR...
But it's fine, no problem =) Thanks for your feedback!

**Comment by asottile** [comment]
could you help me reword this so it's more clear?

>  if you cannot satisfy these requirements do not open a PR

**Comment by RobPasMue** [comment]
Nope, all clear. Thanks again!

**Pull request closed without merging**
