### PR TITLE
Add editorconfig-checker hooks repo

### PR DESCRIPTION
**Pull request by skycaptain**
[editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker) is a tool to verify that your files are in harmony with your [.editorconfig](https://editorconfig.org/).

The repo adds this via the Python wrapper project: https://github.com/editorconfig-checker/editorconfig-checker.python

### CODE REVIEW

**Comment by asottile** [comment]
please attempt to contribute this upstream first, thanks

**Comment by skycaptain** [comment]
https://github.com/editorconfig-checker/editorconfig-checker/issues/133

**Comment by asottile** [comment]
notably: you shouldn't need a mirror or a wrapper as pre-commit supports installing go repositories directly

**Comment by skycaptain** [comment]
@asottile: Ok, didn't know that; but still `.pre-commit-hooks.yaml` is required in their project, right?

**Comment by asottile** [comment]
correct

**Comment by skycaptain** [comment]
@asottile Upstream has merged https://github.com/editorconfig-checker/editorconfig-checker.python/pull/7, which adds `.pre-commit-hooks.yaml` to their project. Would you now be willing to link to their project?

**Comment by asottile** [comment]
yep sounds good -- mind opening a PR for that?

**Pull request closed without merging**
