### PR TITLE
Update all-repos.yaml

### PR DESCRIPTION
**Pull request by JanuszNowak**
Add https://github.com/Azure4DevOps/check-azure-bicep pre-commit for azure bicep

### CODE REVIEW

**Comment by asottile** [comment]
- it's spelled "pre-commit" -- not "Pre-commit"
- `pass_filenames: true` is the default
- `language: script` hooks miss the point of the framework as they require users to install tools outside of the framework to use them and as such I'm not allowing new ones onto the hooks page

**Comment by asottile** [comment]
> There is no support for powershell, you have hooks like for terraform that also require installation ?

...

>  not allowing new ones

**Comment by JanuszNowak** [comment]
@asottile 
I fixed to `pre-commit`, also working on docker version. How can I use `additional_dependencies` to install all required stall like `pip install azure-cli`  ?

**Comment by asottile** [comment]
you wouldn't -- you'd use `language: python` and use actual dependencies

**Pull request closed without merging**
