### PR TITLE
Add pre-commit-yamale

### PR DESCRIPTION
**Pull request by k-ogawa-1988**
I've created a hook for validating YAML by [Yamale](https://github.com/23andMe/Yamale).

### CODE REVIEW

**Comment by asottile** [comment]
hi! this hook has a few problems that would need to be resolved first:

- have you suggested integrating this directly upstream?
- you should not [install pre-commit as a dependency](https://github.com/k-ogawa-1988/pre-commit-yamale/blob/f4c0c9b429b06252abbd4a027fc4b18e71e9d34a/setup.py#L20)
- you should use a different namespace than [pre_commit_hooks](https://github.com/k-ogawa-1988/pre-commit-yamale/blob/f4c0c9b429b06252abbd4a027fc4b18e71e9d34a/pre_commit_hooks/__init__.py) as that's easily confused with pre-commit/pre-commit-hooks
- your `--exclude` recommendations are unnecessary, pre-commit **does not pass files which are not checked in**: https://github.com/k-ogawa-1988/pre-commit-yamale/blame/f4c0c9b429b06252abbd4a027fc4b18e71e9d34a/README.md#L33-L34
- ideally your name should not start with `pre-commit-` as you aren't affiliated with the project: https://github.com/k-ogawa-1988/pre-commit-yamale/blob/f4c0c9b429b06252abbd4a027fc4b18e71e9d34a/setup.py#L6

**Comment by k-ogawa-1988** [comment]
@asottile Thanks for review!

> * have you suggested integrating this directly upstream?

Actually not yet. I saw other PRs and I thought this is okay.

> * you should not [install pre-commit as a dependency](https://github.com/k-ogawa-1988/pre-commit-yamale/blob/f4c0c9b429b06252abbd4a027fc4b18e71e9d34a/setup.py#L20)

Fixed: [here](https://github.com/k-ogawa-1988/yamale-pre-commit/commit/48fd14ce9213880c8eb384d3ed491412af986346#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L20)

> * you should use a different namespace than [pre_commit_hooks](https://github.com/k-ogawa-1988/pre-commit-yamale/blob/f4c0c9b429b06252abbd4a027fc4b18e71e9d34a/pre_commit_hooks/__init__.py) as that's easily confused with pre-commit/pre-commit-hooks

Fixed: [here](https://github.com/k-ogawa-1988/yamale-pre-commit/commit/48fd14ce9213880c8eb384d3ed491412af986346#diff-25fcbf3701641f6facf33b92955a109d61f2faa4e4934b6500baf4c5a5180dbb)

> * your `--exclude` recommendations are unnecessary, pre-commit **does not pass files which are not checked in**: https://github.com/k-ogawa-1988/pre-commit-yamale/blame/f4c0c9b429b06252abbd4a027fc4b18e71e9d34a/README.md#L33-L34

Fixed: [here](https://github.com/k-ogawa-1988/yamale-pre-commit/commit/48fd14ce9213880c8eb384d3ed491412af986346#diff-a514c603ca622745605583d75b217c3b15a26b5a402784dd282aad2f7fdbb48cL22)

> * ideally your name should not start with `pre-commit-` as you aren't affiliated with the project: https://github.com/k-ogawa-1988/pre-commit-yamale/blob/f4c0c9b429b06252abbd4a027fc4b18e71e9d34a/setup.py#L6

Fixed: [here](https://github.com/k-ogawa-1988/yamale-pre-commit/commit/48fd14ce9213880c8eb384d3ed491412af986346#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R6)

**Comment by k-ogawa-1988** [comment]
@asottile Hi, could you process my PR?

**Comment by asottile** [comment]
you haven't done the first thing I asked for yet: https://github.com/23andMe/Yamale/issues?q=is%3Aissue+is%3Aopen+pre-commit

**Comment by k-ogawa-1988** [comment]
@asottile Ah, I have just now understood what you have told me.

**Comment by k-ogawa-1988** [comment]
@asottile Done the first one you pointed.
https://github.com/23andMe/Yamale/issues/163

**Pull request closed without merging**
