### PR TITLE
Added hooks for Fireblade

### PR DESCRIPTION
**Pull request by Firebladee**

### CODE REVIEW

**Comment by asottile** [comment]
https://github.com/shellcheck-py/shellcheck-py is a better implementation of this that's already in the list

**Comment by Firebladee** [comment]
Unfortunately that still needs shellcheck installed on your machine.  One of the hooks I have is to have shellcheck done through docker.
I can remove the normal shellcheck hook if you want.  I only add the normal shellcheck hook as completeness.

**Comment by asottile** [comment]
it does not, try it

**Comment by Firebladee** [comment]
Before I wrote my hook I looked at that and dismissed it as I thought I needed one running through docker.
Oh well.  Thanks for creating pre-commit catches so much stuff.

**Comment by asottile** [comment]
yep yep -- that's why @ryanrhee and I made it -- because shellcheck is so useful and also tricky to install :)

**Pull request closed without merging**
