### PR TITLE
add qt-pre-commit-hooks to all-repos.yaml

### PR DESCRIPTION
**Pull request by nrbnlulu**
add https://github.com/nrbnlulu/qt-pre-commit-hooks to all-repos.yaml

This is a QML formatter.. If there is a way to add QML to the languages it would be nice.

my new repository:

- [ ] is added to the bottom *or* with existing repos from the same account
- [ ] contains a license
- [x] is not `language: system` or `language: docker`
- [ ] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by nrbnlulu** [comment]
what does 
>  is not language: system or language: docker
means? (Sorry for the ignorance..)

**Comment by asottile** [comment]
https://github.com/nrbnlulu/qt-pre-commit-hooks/blob/63b5ea5d1323ee7daf79aa51bc03d2490163509e/.pre-commit-hooks.yaml#L5

**Comment by nrbnlulu** [comment]
Can you reopen and draft this please? I will work on this soon

**Comment by asottile** [comment]
you can make a new PR once things are ready

**Pull request closed without merging**
