### PR TITLE
Add django-ensure-makemessages to all-repos

### PR DESCRIPTION
**Pull request by nils-van-zuijlen**
my new repository:

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system`, `language: script`, or `language: docker`
- [x] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
this isn't a good fit for pre-commit as it requires the user to install things outside of the framework -- plus your `files` regex is wrong

**Comment by nils-van-zuijlen** [comment]
I only found out about the naming requirements in the PR template, should I create an issue for having them in the "Contributing" section?

**Comment by asottile** [comment]
no, the PR template is enough to show the requirement

**Comment by nils-van-zuijlen** [comment]
Fair enough. Do you have an idea about how I can include the gettext dependency ? The other ones (python, manage.py file) should already be dealt with in the context of a django app.

**Comment by asottile** [comment]
it's not those -- it's the "context of a django app" that's the problem -- you have no guarantee that the django app is set up properly and ready to go

**Comment by nils-van-zuijlen** [comment]
Then I don't understand why https://github.com/jguttman94/pre-commit-gradle is in the list as it needs the gradle config to be set up and ready to go.

Also, you don't want to commit code that does not launch either way, no?

**Pull request closed without merging**
