### PR TITLE
TypeScript compiler checker

### PR DESCRIPTION
**Pull request by ggozad**
…er check

my new repository:

- [X] is added to the bottom *or* with existing repos from the same account
- [X] contains a license
- [X] is not `language: system` or `language: docker`
- [X] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
you've checked the 4th checkbox incorrectly

**Comment by asottile** [comment]
and calling `npx tsc` escapes the framework so there's no benefit to this over `language: system`

**Comment by ggozad** [comment]
Hey Anthony, very sorry about this, wasn't paying enough attention. 
I renamed the repo and  removed npx so will  make another pull request.

**Comment by asottile** [comment]
I don't think tsc is a good fit for pre-commit, it's going to be too slow *and* it requires your dependencies be available

**Comment by ggozad** [comment]
Fair enough :)
I thought I would make this available as I could not find an alternative hook for type checking. This is a check that I would guess is very common in js/ts projects. Out of curiosity is there an alternative faster way?

**Pull request closed without merging**
