### PR TITLE
Added `mirrors-pytest` to `all-repos.yaml`

### PR DESCRIPTION
**Pull request by Repiteo**
my new repository:

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system`, `language: script`, `language: docker`, or `language: docker_image`
- [x] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
pytest should not be run with pre-commit

**Comment by Repiteo** [comment]
Damn, couldn't have chosen a more qualified person to shoot this idea down lmao

**Comment by asottile** [comment]
there's a lot of writing about this amongst the pre-commit *and* pytest issue tracker(s) -- here's a short summary: https://github.com/pre-commit/pre-commit-hooks/issues/291#issuecomment-394167917

**Comment by Repiteo** [comment]
D'oh! I only checked the PRs for `pytest`, somehow didn't think to check issues as well. At least my specific use-case is rather small so I can get away with using it for the time being, but I can certainly see why you wouldn't want to "endorse" this practice by adding it officially.

**Pull request closed without merging**
