### PR TITLE
chore: add clang-format-precommit

### PR DESCRIPTION
**Pull request by henryiii**
Uses 1-2 MB PyPI package on all platforms.

Let me know if there's any special ordering you'd like, just stuck it at the end.

### CODE REVIEW

**Comment by asottile** [comment]
at the end is fine -- I would prefer it it were named `clang-format-hook` instead  -- don't want to confuse it with `pre-commit` itself

**Comment by henryiii** [comment]
But `-hook` doesn't really make it clear what it's used for (it's pre-commit specific). I'll check and see if they are interested in moving it. I think it still will work for early adopters if renamed.

**Comment by henryiii** [comment]
I probably inspired the current name by pointing at cmake-format-precommit as an example: https://github.com/ssciwr/clang-format-wheel/issues/8#issue-1009777067

**Comment by asottile** [comment]
alternatively -- if you want to add `types_or` support to https://github.com/pre-commit/pre-commit-mirror-maker then I could create a `mirrors-clang-format` and then we wouldn't need any external management

**Comment by henryiii** [comment]
x-ref: https://github.com/pre-commit/pre-commit-mirror-maker/issues/69

**Comment by asottile** [comment]
thanks for the work on `types_or` -- I set this up using it!  https://github.com/pre-commit/mirrors-clang-format

**Comment by dokempf** [comment]
Hey, @asottile thanks for setting up this mirror. I prefer this option over the current solution of having a separate repository in the same namespace as the packaging repo (https://github.com/ssciwr/clang-format-hook). I would prefer to have the possibility to write a custom (less generic) Readme though. Would you accept PRs to this mirror repo or consider adding me to the repo so that I can edit the Readme? (I maintain the packaging repo https://github.com/ssciwr/clang-format-wheel)

**Comment by asottile** [comment]
yeah feel free to send PRs -- though usually I try and keep the readmes as simple as possible and direct issues to the parent repositories (unless of course it's a bug in the configuration)

**Pull request closed without merging**
