### PR TITLE
feat: Add dc-avro lint

### PR DESCRIPTION
**Pull request by svdimchenko**
Add dc-avro to lint avro schemas in pre-commit

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system`, `language: script`, `language: docker`, or `language: docker_image`
- [x] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
your regex in your `.pre-commit-hooks.yaml` is not correct -- it would disallow files with whitespace in them

**Comment by svdimchenko** [comment]
Current regex `\S+\.avsc$` does not allow whitespace and that's OK for avro schema files. Could you provide and example when do you need to keep whitespace ?

**Comment by asottile** [comment]
`my schema.avsc`

**Comment by svdimchenko** [comment]
ah, I've never met such naming for avro schemas. So feel free to open an issue in corresponding repo.

**Pull request closed without merging**
