### PR TITLE
docs: add swiftformat hook

### PR DESCRIPTION
**Pull request by levibostian**
I created one pre-commit hook for [swiftformat](https://github.com/nicklockwood/SwiftFormat). This PR is to add the repo to the site for other swift devs to find.

### CODE REVIEW

**Comment by levibostian** [comment]
Not sure why the CI build failed? From the error logs, I can't see the problem.

**Comment by asottile** [comment]
ah, it looks like you linked your own repo instead of the swiftformat one, perhaps that's why it's failing?  I'm not sure why there's no output of that though 🤔

**Comment by asottile** [comment]
not sure why the error didn't show up, there was a hook which incorrectly set `verbose: true` (I've since fixed it)

**Comment by levibostian** [comment]
🤦......

I can't believe that I am *just now* realizing that the [swiftformat](https://github.com/nicklockwood/SwiftFormat/blob/master/.pre-commit-hooks.yaml) project has it's own hooks file.......

Yesterday was my very first day using pre-commit so I guess beginner's mistake. I made my own repo for noting! But, hey. I learned a lot and had a pleasant experience working with pre-commit. Bonus: The official repo got added to the site. 

Thanks for catching that.

**Comment by asottile** [comment]
no problem!  thanks for the PR 🎉

**Pull request merged**
