### PR TITLE
docs: add new repository hooks

### PR DESCRIPTION
**Pull request by Gabitchov**
This PR add mine hooks repository that contains a EClint hook, so far.

### CODE REVIEW

**Comment by asottile** [comment]
seems like eclint is dead / deprecated -- I'm not sure we'd want to advertise an integration with it -- thoughts?

**Comment by Gabitchov** [comment]
Indeed, it seems that the creator abandoned his project so I will add a recent one like editorconfig-checker. I didn't take attention to the ticket where the creator mentioned that he didn't maintain anymore this project.

**Comment by asottile** [comment]
looks like that's in progress currently here: https://github.com/editorconfig-checker/editorconfig-checker.python/pull/7/files

**Comment by Gabitchov** [comment]
I created a asdf plugin to intall the editorconfig-checker command easily and avoid all those wrappers. I will change my precommit hook to a bash one to call the binary command.
https://github.com/Gabitchov/asdf-editorconfig-checker

**Comment by Gabitchov** [comment]
I modified my work to use a bash script. It seems to work for my purpose. If the hook can be hosted by the main project, I close my PR and I am waiting the merge this PR. Thanks for your time.

**Pull request closed without merging**
