### PR TITLE
Adds checkmake repo

### PR DESCRIPTION
**Pull request by colindean**
checkmake got a hook configuration in https://github.com/mrtazz/checkmake/commit/4e37f3a6ea00208b3f5bd04eaa0f075068237f18

my new repository:

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system` or `language: docker`
- [x] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
`pass_filenames: false` is incorrect I believe -- the tool should operate on files passed to it

**Comment by colindean** [comment]
Where are you seeing that?

Looks like it's set to `true` [here](https://github.com/mrtazz/checkmake/blob/4e37f3a6ea00208b3f5bd04eaa0f075068237f18/.pre-commit-hooks.yaml#L5).

**Comment by asottile** [comment]
ah I think I just misread -- `pass_filenames: true` is the default so you shouldn't need to set it

is there a reason that `types: [makefile]` wasn't used?

**Comment by colindean** [comment]
Looks like `*.make`, declared [here](https://github.com/mrtazz/checkmake/commit/4e37f3a6ea00208b3f5bd04eaa0f075068237f18#diff-cb921d5df435fe404b4daf451cf783709ccebe9c346038af6036644e7386c13dR10), is missing from the extension list [here](https://github.com/pre-commit/identify/blob/e834194e383eb683ad73a1d0324aaf66942edc8c/identify/extensions.py#L137) but the filenames are listed [here](https://github.com/pre-commit/identify/blob/e834194e383eb683ad73a1d0324aaf66942edc8c/identify/extensions.py#L321-L328) adequately.

I've proposed adding `.make` in https://github.com/pre-commit/identify/pull/353 and switching to the `types` property in https://github.com/mrtazz/checkmake/pull/77. It might be a hot minute before 353 makes it into a pre-commit release but I think that's OK because I've rarely seen `.make` and the change in checkmake is so recent that I doubt that anyone who's adopted the pre-commit hook already relies on it.

**Comment by asottile** [comment]
identify has been released so you should be able to use `types` now

**Pull request merged**
