### PR TITLE
Add `git-lfs-hooks-mirror` to the supported hooks

### PR DESCRIPTION
**Pull request by KAUTH**
These hooks mirror the Git LFS hooks.

This includes four hook types:
- post-checkout
- post-commit
- post-merge
- pre-push

my new repository:

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system` or `language: docker`
- [x] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
you've checked this box but not followed it: `does not contain "pre-commit" in the name`

**Comment by KAUTH** [comment]
> you've checked this box but not followed it: `does not contain "pre-commit" in the name`

I renamed the repository yesterday from `pre-commit-mirrors-git-lfs-hooks` to `precommit-mirrors-git-lfs-hooks`, removing the hyphen, but I guess I followed the letter of the law but not the spirit of the law.

Should I remove it (edit the name of my repo) and re-push?

**Comment by KAUTH** [comment]
I removed the pre-commit reference from the repo name in general. Let me know if there's anything else I should do 😃

**Comment by KAUTH** [comment]
> why does it say "mirror" in a bunch of places?

"Mirror" in the sense that the `git-lfs` repo does not expose its hooks with a `.pre-commit-hooks.yaml` file, so I did this with this repo.

>  also this uses language: script which is not portable

I have checked in Linux and Windows and the hoos installed by `git-lfs` are basically shell scripts, e.g., `pre-push`:
```shell
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
```
That is the reason `language: script` was used.

**Comment by asottile** [comment]
the "mirrors" are repos which lock their version to a particular package -- yours does not do that

also you probably want `pass_filenames: false` -- and they should be written in not-shell so they are up to the quality and portability that's acceptable for the website list

**Comment by KAUTH** [comment]
> the "mirrors" are repos which lock their version to a particular package -- yours does not do that

Oh, I did not realize that. Indeed, my repo tags and provides the same version of hooks as `git-lfs` but does not lock to the specified package. I will change the name of the repo.

> also you probably want `pass_filenames: false` 

Nice, thanks for the tip

> -- and they should be written in not-shell so they are up to the quality and portability that's acceptable for the website list

I see, indeed using `language: script` would not give portability. I think I can run the original git-lfs hook shell scripts, which should remain unchanged, using `language: python`.

Thanks for your time and feedback. I will re-work this a bit and update the PR accordingly.

**Comment by KAUTH** [comment]
After some changes:
- All incorrect references of "mirror repo" have been removed and the docs have been updated
- The repo name has been adjusted accordingly
- We make use of `pass_filenames: false`
- The hooks' `language` type has been changed to `python`
(also tested the hook on Windows and Linux-based OS)

Is there anything else I could do?

**Comment by asottile** [comment]
as far as I can tell it is still a bunch of fragile shell scripts

**Comment by asottile** [comment]
> I followed the letter of the law but not the spirit of the law

stop doing this, it's a waste of my time

**Comment by KAUTH** [comment]
Almost all of the shell scripts are just part of implementing a workflow to automate checking the `git-lfs` repository, and doing some other automation, such as updating my `CHANGELOG.md`.
Now, the rest of the shell scripts are the actual shell scripts provided by `git-lfs` as hooks.

While writing this PR, I found some blanks in pre-commit's documentation which I filled with my other 2 previous PRs that are now merged. With these contributions to the documentation I wanted to help other people that might come accross the same issues as me in this useful tool, pre-commit.

In any case, if this is how you feel, I am closing this PR.

**Pull request closed without merging**
