### PR TITLE
Add pre-commit hooks for android-kotlin

### PR DESCRIPTION
**Pull request by jggomez**
Add pre-commit hooks for android-kotlin

https://github.com/jggomez/pre-commit-android-kotlin
Screen Shot 2021-04-13 at 23 15 13

### CODE REVIEW

**Comment by asottile** [comment]
your `unittests` hook can be replaced with:

```
language: system
entry: ./gradlew test
pass_filenames: false
always_run: true
```

actually, probably most of them can be adjusted to that as well?  as they're written right if you stage a lot of filenames you'll get multiple invocations of each (try with `--verbose`)

**Comment by jggomez** [comment]
Ok, I have remove the script directory. Thanks

**Comment by jggomez** [comment]
> your `unittests` hook can be replaced with:
> 
> ```
> language: system
> entry: ./gradlew test
> pass_filenames: false
> always_run: true
> ```
> 
> actually, probably most of them can be adjusted to that as well? as they're written right if you stage a lot of filenames you'll get multiple invocations of each (try with `--verbose`)

Hi, are there other any issues?

**Review by asottile — APPROVED** [review]

**Pull request merged**
