### PR TITLE
Adding https://github.com/tarioch/flux-check-hook

### PR DESCRIPTION
**Pull request by tarioch**

### CODE REVIEW

**Comment by asottile** [comment]
please don't use `pre-commit-hooks` or `pre_commit_hooks` as names

**Comment by asottile** [comment]
your project is susceptible to shell injection: https://github.com/tarioch/pre-commit-hooks/blob/c59afbe0956b4e3bd8844569d2777de6e48f52b8/pre_commit_hooks/check_flux_helm_values.py#L61-L62

**Comment by asottile** [comment]
😆 please don't name your project `pre-commit` either -- you are not officially associated

**Comment by tarioch** [comment]
Sorry about that, I just looked what other repos are named. Any good idea how to name this to make it clear that it's a pre commit hook without having pre commit in the name?

**Comment by asottile** [comment]
sure that seems  fine

**Comment by tarioch** [comment]
Adjusted the repo name

**Pull request merged**
