### PR TITLE
Add clang-format docs to all-repos

### PR DESCRIPTION
**Pull request by finsberg**
my new repository:

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system` or `language: docker`
- [x] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
this already exists: https://github.com/pre-commit/mirrors-clang-format

**Comment by asottile** [comment]
oh I see your thing is different -- you're also violating my LICENSE since it's a derivative work of `blacken-docs` without proper attribute

**Comment by finsberg** [comment]
Sorry about that! I will add the proper attribute asap.

**Comment by finsberg** [comment]
@asottile Added a note about `blacken-docs` in the [README](https://github.com/finsberg/clang-format-docs/blob/main/README.md)

**Comment by asottile** [comment]
in order to comply with the LICENSE you need to include the original LICENSE bytes in your copy: https://github.com/adamchainz/blacken-docs/blob/79ef671d15161b9dbc16ac3760086b5222836583/LICENSE#L10-L11

the easiest is to make a `./licenses` and include it there -- here's how I do that for `babi-grammars` for example: 

- license file: https://github.com/asottile/babi-grammars/blob/608e91bdd7efde8b92f90a226180463f197a6ef5/licenses/LICENSE_Dart-Code_Dart-Code#L1
- included in setuptools metadata: https://github.com/asottile/babi-grammars/blob/608e91bdd7efde8b92f90a226180463f197a6ef5/setup.cfg#L13

**Comment by finsberg** [comment]
Thanks for guiding me through this. I have now added a file called `LICENSE_blacken_docs` and referred to it in the `README`. Is this OK? https://github.com/finsberg/clang-format-docs

**Comment by asottile** [comment]
~technically the `license_files` part should happen to, that way it is distributed with your library

**Comment by finsberg** [comment]
OK, should be fixed now: https://github.com/finsberg/clang-format-docs/blob/main/setup.cfg#L12-L13

**Pull request merged**
