### PR TITLE
feat: Add dc-avro lint pre-commit to all-repos

### PR DESCRIPTION
**Pull request by svdimchenko**
Add dc-avro lint pre-commit

my new repository:

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system`, `language: script`, `language: docker`, or `language: docker_image`
- [x] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
it looked like a mistake?

**Comment by asottile** [comment]
no your pr looks like a mistake because it has a bunch of unrelated changes

**Comment by svdimchenko** [comment]
> no your pr looks like a mistake because it has a bunch of unrelated changes

okay, you can keep it closed then. However I think `.gitignore` contains bunch of misconfiguration then 😄

**Comment by asottile** [comment]
no. my gitignore does not need your junk for tools I don't use

**Pull request closed without merging**
