### PR TITLE
feat: adds hooks for LabVIEW (G)

### PR DESCRIPTION
**Pull request by felipefoz**
my new repository:

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system`, `language: script`, `language: docker`, or `language: docker_image`
- [ ] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by felipefoz** [comment]
Hey, why was this closed?

**Comment by asottile** [comment]
why was it opened?

**Comment by felipefoz** [comment]
Is because of pre-commit in the name? is it a hard requirement to not have pre-commit in the project name or url? It is not clear to me, I was hoping I could clarify that with you before you closing it. :)

**Comment by asottile** [comment]
why do I bother with a pr template if you don't read it

it's there so you don't waste my already limited time to work on open source

but you've decided your time is more important than mine

**Comment by felipefoz** [comment]
Whatever, my question was not answered. If you were not so reactive, I guess you could not spend your time much as other would spend theirs helping.

**Pull request closed without merging**
