### PR TITLE
add dbt-checkpoint to list of repos

### PR DESCRIPTION
**Pull request by MartinGuindon**
my new repository:

- [X] is added to the bottom *or* with existing repos from the same account
- [X] contains a license
- [X] is not `language: system` or `language: docker`
- [X] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
it seems the docs still have the old name?

**Comment by MartinGuindon** [comment]
We're in the process of cleaning that up! This project was more or less abandoned, and we ended up with two organizations who forked the project, willing to take it over. When we realized that, we teamed up to co-manage the project. We are in the process of merging our (diverging) changes together into a new version, and cleaning up the docs and code base to reflect the new name.

There is a redirect from the old repository name so its not breaking. When we're done with the cleanup, it should reduce the confusion.

**Comment by asottile** [comment]
let me know when the dust settles and then this looks fine 👍

**Comment by MartinGuindon** [comment]
Hello @asottile , the cleanup has been done and version 1.1 has been released. We should be good to go here!

**Review by asottile — APPROVED** [review]

**Pull request merged**
