### PR TITLE
Add ruff, python linter written in rust

### PR DESCRIPTION
**Pull request by tgross35**

### CODE REVIEW

**Comment by asottile** [comment]
`lint` is a poor name for a hook id -- it should be identifiable as your project since it is used as a key for selecting / deselecting and in error messages

**Comment by tgross35** [comment]
Talked with the project maintainer, id `ruff` was added  `and `lint` was marked deprecated (will be removed in about a month)

First version with this new id will be released at 0:00 utc (v0.0.86)

**Comment by charliermarsh** [comment]
@asottile - This got changed from `lint` to `ruff` -- any chance we can add to the list?

**Comment by asottile** [comment]
yep!  should be good to go now -- just needs a rebase.  it wasn't ready when I was pinged so I didn't get a chance to look at this

**Comment by charliermarsh** [comment]
@asottile - No prob at all. I can't edit this PR, easier for me to just open a new one?

**Comment by asottile** [comment]
I'll just rebase this then, one sec

**Comment by charliermarsh** [comment]
Rock, thanks @asottile

**Pull request merged**
