### PR TITLE
add isops, a sops secrets checker

### PR DESCRIPTION
**Pull request by lorenzophys**
My first contribution to the pre-commit community:

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system` or `language: docker`
- [x] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by asottile** [comment]
- `pre-commit` is misspelled -- it is not capitalized
- `pass_filenames: false` misses the point of the framework, tools should take positional arguments of files to check

**Comment by lorenzophys** [comment]
Hey @asottile I see your point, although when dealing with sops the list of files to check is determined by the sops config file: it's not possible to know what files need to be checked when running the command without first parsing the config file.

Of course you can just list them manually when you configure the hook, but a tool like this is needed exactly because you might forget one of the files that you need to check before `git commit`. :D 

Does this make sense?

**Comment by asottile** [comment]
it's not acceptable on the hooks page if it doesn't gel nicely with the framework so I can't accept it in the current state

**Comment by lorenzophys** [comment]
Fair enough! I'm closing

**Pull request closed without merging**
