### PR TITLE
all-repos.yaml add format-ipy-cells hook

### PR DESCRIPTION
**Pull request by janosh**
Code formatter for cell delimiters in interactive iPython notebooks (`# %%`).

### CODE REVIEW

**Review by asottile — APPROVED** [review]
I would recommend renaming your top level module from `hooks` to something unique so you don't collide when installed outside of pre-commit.  also you're using `find_namespace:` but you don't have namespace packages

**Comment by janosh** [comment]
Thanks for the advice. Moved `format_ipy_cells.py` to root level and removed `find_namespace` in https://github.com/janosh/format-ipy-cells/commit/e073a0479617169b24a99d87bd8ea9f31ea02edd.

**Comment by asottile** [comment]
you'll want `py_modules` if you do that btw

**Comment by janosh** [comment]
Changed my mind afterwards. Splitting into `main.py` and `helpers.py` inside `format_ipy_cells/` made it easier to work with. Good to know about `py_modules` for the future though.

**Comment by asottile** [comment]
you still want `find:` and not `find_namespace:` -- the latter is only for namespace packages: https://github.com/pre-commit/pre-commit/blob/fe436f1eb09dfdd67032b4f9f8dfa543fb99cf06/setup.cfg#L24

**Comment by asottile** [comment]
oh I guess it is, but you  probably don't want it to be a namespace package?  you're not going to add another thing under `format_ipy_cells/` in a different package right?

**Comment by janosh** [comment]
No but I also don't like to add `__init__.py` files. They offend my sensibilities. 😆

**Pull request merged**
