### PR TITLE
Added add-msg-issue-suffix-hook

### PR DESCRIPTION
**Pull request by rnjesuz**
pre-commit hook that suffixes Jira issues to the commit message

### CODE REVIEW

**Comment by asottile** [comment]
there's already at least two hooks which accomplish this already in the hooks html -- consider contributing to those!

**Comment by rnjesuz** [comment]
> 
> 
> there's already at least two hooks which accomplish this already in the hooks html -- consider contributing to those!

Can you point me to them? 
The only one I'm seeing is https://github.com/avilaton/add-msg-issue-prefix-hook, which prefixes the jira issue. Mine suffixes it.
But mine also does a little more. As of last release it allows for optionally appending the issue's title as well as it's name

**Comment by asottile** [comment]
> 
> 
> > there's already at least two hooks which accomplish this already in the hooks html -- consider contributing to those!
> 
> Can you point me to them? The only one I'm seeing is https://github.com/avilaton/add-msg-issue-prefix-hook, which prefixes the jira issue. Mine suffixes it. But mine also does a little more. As of last release it allows for optionally appending the issue's title as well as it's name

seems like your extensions would be an easy PR to that  one!

**Comment by rnjesuz** [comment]
> 
> 
> seems like your extensions would be an easy PR to that one!

Doesn't seem trivial to me, especially with my added feature. It would need some refactoring and conditional checking.
I'm content with the state of the repo. 
You can deny the PR if you still don't think it's adding anything new.

**Comment by asottile** [comment]
yeah I would prefer collaboration rather than fork/competition

**Pull request closed without merging**
