### PR TITLE
Add pydantic-hooks repo to all-repos.yaml file

### PR DESCRIPTION
**Pull request by Mermeid-Designs**
my new repository:

- [x] is added to the bottom *or* with existing repos from the same account
- [x] contains a license
- [x] is not `language: system`, `language: script`, `language: docker`, or `language: docker_image`
- [x] does not contain "pre-commit" in the name

### CODE REVIEW

**Comment by Mermeid-Designs** [comment]
Sorry about the [earlier PR](https://github.com/pre-commit/pre-commit.com/pull/875). I misread the last line.

**Comment by asottile** [comment]
the hook specifies `additional_dependencies` but that doesn't seem right -- those should come from your packaging metdata

**Comment by Mermeid-Designs** [comment]
You're right, sorry about that. Fixed by moving it to the setup.cfg.

**Review by asottile — APPROVED** [review]

**Pull request merged**
